import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const TEAL = rgb(13 / 255, 148 / 255, 136 / 255);
const DARK = rgb(55 / 255, 65 / 255, 81 / 255);
const MUTED = rgb(107 / 255, 114 / 255, 128 / 255);

const SECTIONS: Array<[string, string]> = [
  ["Chief Complaint", "chief_complaint"],
  ["History of Present Illness", "hpi"],
  ["On Direct Questioning", "on_direct_questioning"],
  ["Past Medical History", "past_medical_history"],
  ["Past Surgical History", "past_surgical_history"],
  ["Drug History", "drug_history"],
  ["Medications", "medications"],
  ["Allergies", "allergies"],
  ["Family History", "family_history"],
  ["Social History", "social_history"],
  ["Nutritional History", "nutritional_history"],
  ["Immunization History", "immunization_history"],
  ["Developmental History", "developmental_history"],
  ["Gynecological History", "gynecological_history"],
  ["Obstetric History", "obstetric_history"],
  ["Laboratory Investigations", "lab_investigations"],
  ["Imaging Investigations", "imaging_investigations"],
  ["Investigation Comments", "investigation_comments"],
  ["Provisional Diagnosis", "provisional_diagnosis"],
  ["Differential Diagnosis", "differential_diagnosis"],
  ["Final Diagnosis", "final_diagnosis"],
  ["Assessment", "assessment"],
  ["Plan", "plan"],
  ["Recommended Plan (AI)", "recommended_plan"],
  ["SBAR Summary", "sbar_summary"],
  ["Primary Survey", "primary_survey"],
  ["Secondary Survey", "secondary_survey"],
  ["Follow-up", "follow_up"],
];

function stringifySection(value: unknown): string {
  if (value == null) return "";
  if (typeof value === "string") return value;
  if (typeof value === "object") {
    return Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${typeof v === "string" ? v : JSON.stringify(v)}`)
      .join("\n");
  }
  return String(value);
}

export async function generateClinicalPdf(input: {
  note: Record<string, unknown>;
  encounter: { encounter_id: string; date: string; specialty_template: string; duration_seconds: number };
  physician: { full_name: string; credentials: string; specialty: string; institution: string };
  patientLabel: string;
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 612;
  const pageHeight = 792;
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let page = doc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  const ensureSpace = (needed: number) => {
    if (y - needed < margin + 24) {
      page = doc.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }
  };

  const drawWrapped = (text: string, size: number, color = DARK, useBold = false) => {
    const face = useBold ? bold : font;
    const words = text.replace(/\r/g, "").split(/\s+/);
    let line = "";
    const flush = (chunk: string) => {
      ensureSpace(size + 6);
      page.drawText(chunk, { x: margin, y, size, font: face, color, maxWidth });
      y -= size + 4;
    };
    for (const word of words) {
      const next = line ? `${line} ${word}` : word;
      if (face.widthOfTextAtSize(next, size) > maxWidth && line) {
        flush(line);
        line = word;
      } else {
        line = next;
      }
    }
    if (line) flush(line);
  };

  page.drawRectangle({ x: 0, y: pageHeight - 64, width: pageWidth, height: 64, color: TEAL });
  page.drawText("MedScribe — Clinical Note", {
    x: margin,
    y: pageHeight - 40,
    size: 16,
    font: bold,
    color: rgb(1, 1, 1),
  });
  y = pageHeight - 84;

  drawWrapped(`Encounter: ${input.encounter.encounter_id}    Date: ${input.encounter.date}`, 10, MUTED);
  drawWrapped(
    `Physician: ${input.physician.full_name} ${input.physician.credentials}  |  ${input.physician.specialty}`,
    10,
    MUTED
  );
  if (input.physician.institution) drawWrapped(input.physician.institution, 10, MUTED);
  drawWrapped(`Patient: ${input.patientLabel}`, 10, MUTED);
  drawWrapped(`Template: ${input.encounter.specialty_template}`, 10, MUTED);
  y -= 8;

  const disclaimer = String(input.note.ai_disclaimer ?? "This note was generated by AI and requires physician review.");
  drawWrapped(disclaimer, 9, rgb(180 / 255, 83 / 255, 9 / 255));
  y -= 8;

  for (const [label, key] of SECTIONS) {
    const body = stringifySection(input.note[key]).trim();
    if (!body || body === "[NOT DISCUSSED]" || body === "[N/A - Regular Encounter]") continue;
    ensureSpace(28);
    drawWrapped(label.toUpperCase(), 11, TEAL, true);
    for (const paragraph of body.split("\n")) {
      if (paragraph.trim()) drawWrapped(paragraph.trim(), 10);
    }
    y -= 6;
  }

  y -= 10;
  drawWrapped("Physician sign-off", 11, TEAL, true);
  drawWrapped(
    input.note.signed_off_at
      ? `Signed: ${String(input.note.signed_off_at)}`
      : "Not signed — draft for review only.",
    10
  );

  const pages = doc.getPages();
  pages.forEach((p, i) => {
    p.drawText(`Page ${i + 1} of ${pages.length}  |  Confidential clinical document`, {
      x: margin,
      y: 24,
      size: 8,
      font,
      color: MUTED,
    });
  });

  return doc.save();
}
