/**
 * Shared UI Components — Reusable across the entire application.
 *
 * ErrorBoundary: Catches React rendering errors gracefully
 * LoadingSpinner: Consistent loading indicator
 * StatusBadge: Encounter/note status indicator
 * AIDisclaimer: Standard AI-generated content warning
 * ConsentBanner: Consent recording UI
 */

import React, { Component, ReactNode } from 'react';
import { AlertTriangle, Loader2, Shield, Info } from 'lucide-react';
import clsx from 'clsx';
import { STATUS_COLORS } from '../../utils';

// === Error Boundary ===

interface ErrorBoundaryProps {
  children: ReactNode;
  fallback?: ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
}

export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, info: React.ErrorInfo): void {
    // Log error without PHI
    console.error('MedScribe UI Error:', error.message);
  }

  render(): ReactNode {
    if (this.state.hasError) {
      return this.props.fallback || (
        <div className="flex flex-col items-center justify-center p-12 text-center">
          <AlertTriangle className="w-12 h-12 text-amber-500 mb-4" />
          <h2 className="text-lg font-semibold text-slate-800 mb-2">Something went wrong</h2>
          <p className="text-sm text-slate-500 mb-4 max-w-md">
            An unexpected error occurred. Please refresh the page or contact support if the issue persists.
          </p>
          <button
            onClick={() => window.location.reload()}
            className="btn-primary"
          >
            Refresh Page
          </button>
        </div>
      );
    }
    return this.props.children;
  }
}

// === Loading Spinner ===

interface LoadingSpinnerProps {
  size?: 'sm' | 'md' | 'lg';
  message?: string;
  className?: string;
}

export function LoadingSpinner({ size = 'md', message, className }: LoadingSpinnerProps) {
  const sizeMap = { sm: 'w-4 h-4', md: 'w-6 h-6', lg: 'w-10 h-10' };
  return (
    <div className={clsx('flex flex-col items-center justify-center gap-3', className)}>
      <Loader2 className={clsx(sizeMap[size], 'text-teal-600 animate-spin')} />
      {message && <p className="text-sm text-slate-500">{message}</p>}
    </div>
  );
}

// === Status Badge ===

interface StatusBadgeProps {
  status: string;
  className?: string;
}

export function StatusBadge({ status, className }: StatusBadgeProps) {
  const config = STATUS_COLORS[status] || { bg: 'bg-slate-100', text: 'text-slate-700', label: status };
  return (
    <span className={clsx(
      'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
      config.bg, config.text, className
    )}>
      {config.label}
    </span>
  );
}

// === AI Disclaimer ===

interface AIDisclaimerProps {
  text?: string;
  variant?: 'warning' | 'info';
}

export function AIDisclaimer({
  text = 'This note was generated by AI and requires physician review before finalization.',
  variant = 'warning',
}: AIDisclaimerProps) {
  return (
    <div className={clsx(
      'flex items-center gap-3 p-3 rounded-xl text-sm',
      variant === 'warning'
        ? 'bg-amber-50 border border-amber-200 text-amber-800'
        : 'bg-blue-50 border border-blue-200 text-blue-800'
    )}>
      {variant === 'warning' ? (
        <AlertTriangle className="w-4 h-4 flex-shrink-0" />
      ) : (
        <Info className="w-4 h-4 flex-shrink-0" />
      )}
      <span>{text}</span>
    </div>
  );
}

// === Consent Banner ===

interface ConsentBannerProps {
  onConsent: (consented: boolean) => void;
  isRecording?: boolean;
}

export function ConsentBanner({ onConsent, isRecording = false }: ConsentBannerProps) {
  if (isRecording) return null;

  return (
    <div className="p-4 rounded-xl bg-teal-50 border border-teal-200">
      <div className="flex items-start gap-3">
        <Shield className="w-5 h-5 text-teal-600 mt-0.5 flex-shrink-0" />
        <div className="flex-1">
          <p className="text-sm font-medium text-teal-800">Patient Consent Required</p>
          <p className="text-xs text-teal-600 mt-1">
            Confirm that the patient has been informed about and consents to
            AI-assisted clinical documentation for this encounter.
          </p>
          <div className="flex gap-2 mt-3">
            <button onClick={() => onConsent(true)} className="btn-primary py-1.5 px-4 text-sm">
              Consent Given
            </button>
            <button onClick={() => onConsent(false)} className="btn-secondary py-1.5 px-4 text-sm">
              Consent Declined
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// === Empty State ===

interface EmptyStateProps {
  icon?: ReactNode;
  title: string;
  description?: string;
  action?: ReactNode;
}

export function EmptyState({ icon, title, description, action }: EmptyStateProps) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      {icon && <div className="mb-4 text-slate-300">{icon}</div>}
      <p className="text-slate-600 font-medium">{title}</p>
      {description && <p className="text-sm text-slate-400 mt-1 max-w-sm">{description}</p>}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}

// === Section Editor ===

interface NoteSectionProps {
  label: string;
  content: string | Record<string, string>;
  isMissing?: boolean;
  isUncertain?: boolean;
  isLocked?: boolean;
  onEdit?: () => void;
}

export function NoteSection({
  label, content, isMissing, isUncertain, isLocked,
}: NoteSectionProps) {
  return (
    <div className={clsx(
      'p-4 rounded-xl border',
      isLocked ? 'bg-slate-50 border-slate-200 opacity-75' :
      isMissing ? 'bg-amber-50/50 border-amber-300 border-dashed' :
      isUncertain ? 'bg-amber-50/30 border-amber-400' :
      'bg-white border-slate-200'
    )}>
      <h4 className="section-header flex items-center gap-2">
        {label}
        {isMissing && (
          <span className="badge bg-amber-100 text-amber-800 text-[10px]">Not Discussed</span>
        )}
        {isUncertain && (
          <span className="badge bg-amber-100 text-amber-800 text-[10px]">Uncertain</span>
        )}
      </h4>
      <div className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">
        {isMissing || !content
          ? <span className="text-slate-400 italic">[Not discussed during encounter]</span>
          : typeof content === 'object'
            ? Object.entries(content).map(([k, v]) => (
                <div key={k} className="mb-1">
                  <span className="font-medium text-slate-600">{k.replace(/_/g, ' ')}:</span> {v}
                </div>
              ))
            : content
        }
      </div>
    </div>
  );
}
